version: "3.9"

services:
  node_backend:
    container_name: reservApp
    image: "node:16"
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PG_NAME=reservapp
      - PG_USER=tugerente
      - PG_PASSWORD=admin
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tugerente
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reservapp
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}
